version: "3"
services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reverse-proxy/basic_auth:/etc/nginx/basic_auth:ro
  static_serving:
    image: nginx:alpine
    ports:
      - "8081:8080"
    volumes:
      - ./static-serving/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app-server/public:/var/www/nginx/html/public:ro
  full_cache:
    image: nginx:alpine
    ports:
      - "8082:8080"
    volumes:
      - ./full-cache/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app-server/public:/var/www/nginx/html/public:ro
      - ./full-cache/cache:/var/tmp
  error_handling:
    image: nginx:alpine
    ports:
      - "8083:8080"
    volumes:
      - ./error-handling/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./error-handling/basic_auth:/etc/nginx/basic_auth:ro
